#!/bin/bash

executable="./$(basename `pwd`)"
cases=`find test/fixtures/in/* -exec basename {} .txt \;`

tst() {
  cat test/fixtures/in/$1.txt \
    | $executable \
    | diff $(echo test/fixtures/out/$1.txt) -
}

if [ $1 ]; then
  tst $1
else
  for test_case in $cases; do
    tst $test_case
  done
fi
